### ISSUE TITLE
neptune 2s Firmware including elegoo_font and _pic

### ISSUE THREAD

**Issue by anone1984** [NARUTOfzr/ZNP-Robin-Nano-V1.2-V1.3#4]
hey there!
Heres the Topic in Issues!
Thanks for your fast reply, hope its right here.

Tried flashing the elegoo.bin already from the (1.3 Folder 2.0.2). Screen stays black and nothing happens anymore. even after trying to reflash, it just stays flashing 100% and nothing happens anymore.
Tried with two different SDCards.
Andreas Wiechmann

**Comment by NARUTOfzr** [comment]
[Neptune2S.zip](https://github.com/NARUTOfzr/ZNP-Robin-Nano-V1.2-V1.3/files/10045734/Neptune2S.zip)
First confirm that your board version is ZNP-Robin-Nano-V1.3 before loading this firmware.你先试一试

**Comment by anone1984** [comment]
Jop, its the V1.3 Thanks man! That solved the problem and the flash just worked fine!

**Comment by NARUTOfzr** [comment]
@anone1984 
Are you flashing V2.0.1 or V2.0.2?

**Comment by anone1984** [comment]
i was flashing V2.0.2 right now. the files you provided solved the problem. Everything seems to work fine again so far. the problems happened after installing the mks robin wifi 1.1 module. but i'll just leave it stock now. the files from the elegoo homepage didn't work so far.

**Comment by NARUTOfzr** [comment]
Thanks for your feedback!You can try to reinstall the WiFi module. Then flash the firmware.
If it still doesn't work, there's nothing I can do.

[Neptune2S_wifi.zip](https://github.com/NARUTOfzr/ZNP-Robin-Nano-V1.2-V1.3/files/10045796/Neptune2S_wifi.zip)
